language: node_js
sudo: false
node_js:
  - node

script:
  - npm run build:prod

cache: npm

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: dist
  name: Niklas Mollenhauer
  email: nikeee@outlook.com
  project-name: edotor.net
  on:
    branch: master
    tags: true
